import json
from pathlib import Path

import httpx
from bs4 import BeautifulSoup

CORPUS_FILE = Path(__file__).parent / "corpus.json"
MIN_PARAGRAPH_LEN = 80
USER_AGENT = "climate-impacts-agent-demo/0.1 (portfolio project)"

# Real sources only. GISS pages carry "Agriculture" (Rosenzweig/Ruane/De Mel's Climate Impacts
# Group at NASA GISS works on agriculture, food security, and urban climate risk — not general
# biome/vegetation dynamics, so that side of the corpus draws from general NASA climate content
# instead, tagged "Biome" and "General" for the driver-level (temp/precip/heat/drought) grounding
# both sectors need).
SOURCES = [
    {
        "url": "https://www.giss.nasa.gov/projects/impacts/",
        "selector": "#content",
        "title": "NASA GISS Climate Impacts Group",
        "tags": ["Agriculture"],
    },
    {
        "url": "https://www.giss.nasa.gov/staff/crosenzweig.html",
        "selector": "#content",
        "title": "Cynthia Rosenzweig — NASA GISS",
        "tags": ["Agriculture"],
    },
    {
        "url": "https://www.giss.nasa.gov/staff/aruane.html",
        "selector": "#content",
        "title": "Alex Ruane — NASA GISS",
        "tags": ["Agriculture"],
    },
    {
        "url": "https://www.giss.nasa.gov/staff/jdemel.html",
        "selector": "#content",
        "title": "J. Manishka De Mel — NASA GISS",
        "tags": ["Agriculture", "Biome"],
    },
    {
        "url": "https://www.nasa.gov/earth-and-climate/global-climate-change-impact-on-crops-expected-within-10-years-nasa-study-finds/",
        "selector": ".entry-content",
        "title": "Global Climate Change Impact on Crops Expected Within 10 Years (NASA, 2021)",
        "tags": ["Agriculture"],
    },
    {
        "url": "https://www.nasa.gov/earth-and-climate/nasa-at-your-table-climate-change-and-its-environmental-impacts-on-crop-growth/",
        "selector": ".entry-content",
        "title": "NASA at Your Table: Climate Change and Its Environmental Impacts on Crop Growth (NASA, 2021)",
        "tags": ["Agriculture"],
    },
    {
        "url": "https://climate.nasa.gov/effects/",
        "selector": ".entry-content",
        "title": "Effects of Climate Change (NASA)",
        "tags": ["Biome", "General"],
    },
    {
        "url": "https://climate.nasa.gov/vital-signs/",
        "selector": ".entry-content",
        "title": "Vital Signs of the Planet (NASA)",
        "tags": ["General"],
    },
]


def _fetch_paragraphs(url: str, selector: str) -> list[str]:
    """Real paragraph text from one page, deduplicated and length-filtered.

    Args: url — page to fetch. selector — CSS selector for the main content container.
    Returns: list of cleaned paragraph strings.
    """
    response = httpx.get(url, timeout=20.0, follow_redirects=True, headers={"User-Agent": USER_AGENT})
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    container = soup.select_one(selector)
    if container is None:
        return []

    seen: set[str] = set()
    paragraphs: list[str] = []
    for tag in container.find_all("p"):
        text = tag.get_text(" ", strip=True)
        is_link_list_item = text.startswith("+")  # GISS "News & Features" style link fragments
        if len(text) >= MIN_PARAGRAPH_LEN and text not in seen and not is_link_list_item:
            seen.add(text)
            paragraphs.append(text)
    return paragraphs


def build_corpus() -> list[dict]:
    """Fetch every real source and chunk it into tagged passages.

    Returns: list of {text, source_title, source_url, tags} dicts.
    """
    chunks: list[dict] = []
    for source in SOURCES:
        for paragraph in _fetch_paragraphs(source["url"], source["selector"]):
            chunks.append(
                {
                    "text": paragraph,
                    "source_title": source["title"],
                    "source_url": source["url"],
                    "tags": source["tags"],
                }
            )
    return chunks


def save_corpus(chunks: list[dict]) -> None:
    """Persist chunks to CORPUS_FILE as JSON."""
    CORPUS_FILE.write_text(json.dumps(chunks, indent=2))


def load_corpus() -> list[dict]:
    """Load chunks from CORPUS_FILE.

    No auto-build fallback, unlike embed.py's derived cache — this fetches live external
    content, so (like the climate/agriculture/biome data) it's provisioned explicitly via
    `dvc repro`, not silently regenerated by whichever tool happens to run first.
    """
    return json.loads(CORPUS_FILE.read_text())


def main() -> None:
    chunks = build_corpus()
    save_corpus(chunks)
    print(f"Saved {len(chunks)} chunks to {CORPUS_FILE}")


if __name__ == "__main__":
    main()
